language: ruby
cache:
  directories:
  - "$HOME/.berkshelf"
addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk
before_install:
- openssl aes-256-cbc -K $encrypted_6bddd121d121_key -iv $encrypted_6bddd121d121_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar -xvf secrets.tar -C $HOME
- mv $HOME/.aws/ds_travis_credentials $HOME/.aws/credentials
- echo 'node_name "darksky"' >> $HOME/.chef/knife.rb
- echo "client_key '$HOME/.chef/darksky.pem'" >> $HOME/.chef/knife.rb
- echo 'chef_server_url "https://chef.darksky.net/organizations/darksky"' >> $HOME/.chef/knife.rb
- chmod 600 $HOME/.chef/knife.rb $HOME/.chef/darksky.pem
install:
- berks
before_script:
- chef --version
- eval "$(chef shell-init bash)"
- cookstyle --version
- foodcritic --version
script:
- chef exec kitchen verify
- chef exec kitchen destroy
matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
